# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.provision "file", source: "./id_rsa.pub", destination: "/home/vagrant/.ssh/me.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "rm /home/vagrant/.ssh/me.pub"

  #config.vm.provision "shell", inline: <<-SHELL
  #  echo "#################################"
  #  echo "#      CONFIGURE SWAP FILE      #"
  #  echo "#################################"
  #  sudo dd if=/dev/zero of=/swapfile bs=1M count=1024 && \
  #  sudo chmod 0600 /swapfile && \
  #  sudo chown root:root /swapfile && \
  #  sudo mkswap /swapfile && \
  #  echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
  #  sudo mount -a && \
  #  sudo swapon -a
  #  echo ""
  #  echo "+++++++++++++++++++++++++++++++++"
  #  echo ""
  #  sudo cat /etc/fstab
  #  echo ""
  #  echo "+++++++++++++++++++++++++++++++++"
  #  echo ""
  #  sudo swapon -s
  #  echo ""
  #  echo "#################################"
  #  echo "#################################"
  #  echo ""
  #SHELL
end
